# Generated by Django 3.1.7 on 2021-03-05 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_postform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
