# Generated by Django 3.1.7 on 2021-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210306_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorinfo',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='donorinfo',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
